version: '1.0'
networks:
  bestfriend-bridge:
    name: bestfriend-bridge
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16


services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=banco
    ports:
      - "5000:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      bestfriend-bridge:
        ipv4_address: 172.18.0.20

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      bestfriend-bridge:
        ipv4_address: 172.18.0.30

  bestfriend:
      build:
        context: .
        dockerfile: Dockerfile 
      image: bestfriend_v1
      ports:
        - "8000:8000"
      networks:
        bestfriend-bridge:
          ipv4_address: 172.18.0.10
      